CREATE TABLE CATEGORY (
    NAME VARCHAR(64)   NOT NULL       COMMENT '카테고리명',
    PRIMARY KEY(NAME)
);

CREATE TABLE MENU (
    NAME          VARCHAR(64) NOT NULL COMMENT '메뉴명',
    PRICE         INT          NOT NULL COMMENT '가격',
    PRIME_COST    INT          NOT NULL COMMENT '원가',
    TAX_MODE      TINYINT(1)   NOT NULL COMMENT '세금/면세 상품 여부',
    BARCODE       VARCHAR(64) NULL     COMMENT '바코드',
    CATEGORY_NAME VARCHAR(64) NOT NULL COMMENT 'CATEGORY PK',
    PRIMARY KEY(NAME)
);
ALTER TABLE MENU ADD FOREIGN KEY (CATEGORY_NAME) REFERENCES CATEGORY(NAME);

CREATE TABLE USER (
    USERNAME        VARCHAR(32) NOT NULL,
    PASSWORD        VARCHAR(64) NOT NULL,
    STORE_NAME      VARCHAR(128) NOT NULL,
    STORE_ADDRESS   VARCHAR(128) NOT NULL,
    CREATE_TIME     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    CATEGORIES      VARCHAR(1024) NULL COMMENT 'Category names(cake, cofee..) -> have to parsing',
    PRIMARY KEY(USERNAME)
);

CREATE TABLE PURCHASE (
    ID            INT           NOT NULL AUTO_INCREMENT,
    NAME          VARCHAR(128)  NOT NULL COMMENT '메뉴명',
    BARCODE       VARCHAR(256)  NULL     COMMENT '바코드',
    QUANTITY      INT           NOT NULL COMMENT '수량',
    TOTAL_PRICE   INT           NOT NULL,
    PURCHASE_TIME TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID)
);